# permissions for end users to view custompodsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompodset-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - custompodsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - custompodsets/status
  verbs:
  - get
